openapi: 3.0.3
info:
  title: Pizza API
  description: API for managing pizza orders and related operations
  version: 1.0.0
servers:
  - url: https://func-pizza-api-vqqlxwmln5lf4.azurewebsites.net/api
    description: Local development server
paths:
  /orders:
    get:
      tags:
        - orders
      summary: Get all orders
      description: Returns a list of all orders in the system
      operationId: getOrders
      parameters:
        - name: userId
          in: query
          description: Filter orders by userId
          required: false
          schema:
            type: string
        - name: status
          in: query
          description: Filter orders by status (comma-separated for multiple, e.g. pending,ready)
          required: false
          schema:
            type: string
        - name: last
          in: query
          description: Filter orders created in the last X minutes/hours (e.g. 60m, 2h)
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      tags:
        - orders
      summary: Create a new order
      description: Places a new order with pizzas (requires userId).
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Too many active orders for this user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /orders/{orderId}:   
    get:
      tags:
        - orders
      summary: Get order by ID
      description: Retrieves an order by its ID
      operationId: getOrderById
      parameters:
        - name: orderId
          in: path
          description: ID of the order
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order details found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - orders
      summary: Cancel an order
      description: Cancels an order if it has not yet been started (status must be 'pending')
      operationId: cancelOrder
      responses:
        '200':
          description: Order cancelled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Order cannot be cancelled (not in pending status)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /pizzas:
    get:
      tags:
        - pizzas
      summary: Get all pizzas
      description: Returns a list of all pizzas
      operationId: getPizzas
      responses:
        '200':
          description: List of pizzas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuItem'
  /pizzas/{id}:    
    get:
      tags:
        - pizzas
      summary: Get pizza by ID
      description: Retrieves a specific pizza by its ID
      operationId: getPizzaById
      parameters:
        - name: id
          in: path
          description: ID of the pizza
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Pizza details found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItem'
        '404':
          description: Pizza not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /toppings:
    get:
      tags:
        - toppings
      summary: Get all toppings
      description: Returns a list of all toppings
      operationId: getToppings
      parameters:
        - name: category
          in: query
          description: Filter toppings by category
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of toppings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuItem'
  /toppings/categories:
    get:
      tags:
        - toppings
      summary: Get all topping categories
      description: Returns a list of all topping categories
      operationId: getToppingCategories
      responses:
        '200':
          description: List of topping categories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /toppings/{id}:    
    get:
      tags:
        - toppings
      summary: Get topping by ID
      description: Retrieves a specific topping by its ID
      operationId: getToppingById
      parameters:
        - name: id
          in: path
          description: ID of the topping
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Topping details found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItem'
        '404':
          description: Topping not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse' 
  
components:
  schemas:
    MenuCategory:
      type: string
      enum:
        - pizza
        - drink
        - side
        - topping
    MenuItem:
      type: object
      properties:
        id:
          type: string
          example: "pizza-1"
        category:
          $ref: '#/components/schemas/MenuCategory'
        name:
          type: string
          example: "Margherita Pizza"
        description:
          type: string
          example: "Classic pizza with tomato sauce and mozzarella"
        price:
          type: number
          format: float
          example: 12.99
      required:
        - id
        - category
        - name
        - description
        - price
    OrderStatus:
      type: string
      enum:
        - pending
        - in-preparation
        - ready
        - completed
        - cancelled
      description: "- pending: Order has been created but not yet started - in-preparation: Order is being prepared - ready: Order is ready for pickup - completed: Order has been picked up - cancelled: Order has been cancelled"
    OrderItem:
      type: object
      properties:
        pizzaId:
          type: string
          example: "pizza-1"
        quantity:
          type: integer
          minimum: 1
          example: 1
        extraToppingIds:
          type: array
          items:
            type: string
          description: Optional list of extra topping IDs to add to the pizza
          example: ["topping-1", "topping-2"]
      required:
        - pizzaId
        - quantity
    Order:
      type: object
      properties:
        id:
          type: string
          example: "1618057820123"
        userId:
          type: string
          example: "user123"
        createdAt:
          type: string
          format: date-time
          description: ISO date string of when the order was created
          example: "2025-04-10T14:30:00Z"
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        estimatedCompletionAt:
          type: string
          format: date-time
          description: ISO date string for estimated completion time
          example: "2025-04-10T15:00:00Z"
        totalPrice:
          type: number
          format: float
          example: 22.98
        status:
          $ref: '#/components/schemas/OrderStatus'
      required:
        - id
        - userId
        - createdAt
        - items
        - estimatedCompletionAt
        - totalPrice
        - status
    CreateOrderRequest:
      type: object
      properties:
        userId:
          type: string
          example: "user123"
        items:
          type: array
          items:
            type: object
            properties:
              pizzaId:
                type: string
                example: "pizza-1"
              quantity:
                type: integer
                minimum: 1
                example: 1
              extraToppingIds:
                type: array
                items:
                  type: string
                description: Optional list of extra topping IDs to add to the pizza
                example: ["topping-1", "topping-2"]
            required:
              - pizzaId
              - quantity
      required:
        - userId
        - items
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Order must contain at least one item"
      required:
        - error
